### ISSUE TITLE
 Improved README.md for Better Project Understanding

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [Jay-1409/GTA5CHAT#1]
Hello! @Jay-1409 
I have made some improvements to the README.md file of your project to enhance the documentation. The new version provides a more structured layout and clearer explanations of the project's features and tech stack. This helps users and contributors understand the project better, making it easier to contribute.

Changes Made:-
- Added a structured overview of the project and its features.
- Enhanced the project description and purpose.
- Improved the layout of the tech stack section.
- Added instructions on how to run the project locally.
- Provided details on folder structure and usage.
- Included a feedback section for collecting user responses.

Plz Consider it under Hacktoberfest Accepted 2024

Thank You!

**Comment by Jay-1409** [comment]
Please add screen shots. 
Thanks!

**Comment by harshpareshbhaigosalya** [comment]
Changes Made:-
Updated repository link and project structure details.
Added a structured overview of the project and its features.
Enhanced the project description and purpose.
Improved the layout of the tech stack section.
Added instructions on how to run the project locally.
Provided details on folder structure and usage.
Included a feedback section for collecting user responses.
Thank you @Jay-1409

![Screenshot 2024-10-04 215619](https://github.com/user-attachments/assets/95e271aa-f5af-4ec4-9e57-d003610285ad)
![Screenshot 2024-10-04 215631](https://github.com/user-attachments/assets/19df3164-01a0-439d-971b-e56adcfd4c32)
![Screenshot 2024-10-04 221703](https://github.com/user-attachments/assets/b91510b2-ead2-4c90-8a79-aa152766f4b4)

**Comment by harshpareshbhaigosalya** [comment]
Plz let me know if any changes required!

**Comment by Jay-1409** [comment]
Just change point 6 to python app.py

**Comment by harshpareshbhaigosalya** [comment]
i have changed it plz check it!
Thank You!
