### ISSUE TITLE
I want to improve website performance

### ISSUE THREAD

**Issue by bbimams** [Jay-1409/GTA5CHAT#10]

**Comment by Jay-1409** [comment]
Can you please explain

**Comment by Srijan25** [comment]
can you add this in hackober fest and i can improve it efficienct by storing info in cache and cookies

**Comment by Jay-1409** [comment]
> can you add this in hackober fest and i can improve it efficienct by storing info in cache and cookies

please create a new issue for this

**Comment by bbimams** [comment]
> Can you please explain

fixing codes that are not efficient
