### ISSUE TITLE
Issue: Scrolling Issue - Hidden Characters Not Visible

### ISSUE THREAD

**Issue by ARRY7686** [Jay-1409/GTA5CHAT#11]
### Description:
There is an issue with scrolling on the website where certain characters are hidden and not accessible through the user interface. When the user tries to view more characters, the scroll functionality does not work as expected, making it impossible to scroll down or sideways to reveal these hidden characters.

### Steps to Reproduce:
Attempt to scroll down (or sideways) when more characters are present than are displayed on the screen.
Observe that the scroll does not work, and additional characters remain hidden.

### Expected Behavior:
The scroll should allow the user to smoothly navigate through the list of characters.
All characters, including those hidden, should become visible through the scrolling functionality.

### Actual Behavior:
The scroll does not function as intended, and users are unable to view characters beyond the initial display.

### Possible Areas to Investigate:
Check the CSS overflow properties for containers that display the character list.
Ensure that JavaScript handling of scroll events (if any) is functioning correctly.
Review responsive behavior to ensure that scrolling works across different screen sizes and devices.

### Suggested Fix:
Implement or adjust scrollable container properties (e.g., overflow: scroll;) to allow full scrolling for hidden characters.
Verify that the scrolling behavior works across all browsers and devices.

Environment:
Browser: Microsoft Edge
OS: Windows 11
Device: Desktop
Priority:
High - The issue prevents users from accessing all available characters.

**Comment by ARRY7686** [comment]
Pls assign me this issue and mark it as hacktober fest

**Comment by Jay-1409** [comment]
okay please work on it thanks for your time!!
