### ISSUE TITLE
Improve "About Us" Page Styling for Better Visual Design and Responsiveness

### ISSUE THREAD

**Issue by VAmanjain** [Jay-1409/GTA5CHAT#14]
### Issue Description:
The current styling of the "About Us" page needs improvement to enhance visual design and overall user experience. The page should maintain its gaming theme while becoming more readable, modern, and interactive across different devices. The key areas that need improvement are the layout, typography, hover effects, and responsiveness.

#### Problem Areas:
1. **Team Member Profiles**:
   - Profile cards lack contrast, making the text difficult to read.
   - Typography needs refinement for better readability and visual balance.

2. **Buttons and Icons**:
   - Hover effects on buttons are missing or need enhancement for interactivity.
   - Social media icons (LinkedIn) are not visually aligned or properly spaced.

3. **Background and Theme**:
   - The gaming-themed background needs to blend well with the content, but without compromising text clarity.

4. **Responsiveness**:
   - The page does not display optimally on smaller devices like tablets and mobile phones.
   - Font sizes, padding, and card layouts need adjustments for different screen sizes.

### Proposed Solution:
- Update the profile cards with a dark overlay for better contrast.
- Improve typography and align content for a clean, consistent look.
- Add glowing hover effects to buttons for interactive feedback.
- Ensure the background complements the content and improves readability.
- Make the page fully responsive by adjusting the layout for different screen sizes.

### Expected Outcome:
- Enhanced readability and visual consistency for profile cards.
- Improved user interaction with hover effects.
- A well-balanced design that works across various devices, including desktops, tablets, and mobile phones.

**Comment by Jay-1409** [comment]
ok work on it thank you!!
