### ISSUE TITLE
feat: I want to recreate and improve the chat page 

### ISSUE THREAD

**Issue by pragyananda** [Jay-1409/GTA5CHAT#15]
**Is your feature request related to a problem? Please describe.**
Yes, I chatted with the character, and the page currently looks very simple and not visually appealing.

**Describe the solution you'd like**
I would like to recreate this page to enhance its aesthetics and improve user experience.

**Describe alternatives you've considered**
I haven't considered any alternatives yet, as I believe a complete redesign would be the most effective solution.

**Additional context**
The existing page lacks visual interest and could benefit from a more engaging design. Adding more dynamic elements or modern styling would significantly enhance its overall look and feel.

**Comment by pragyananda** [comment]
i am working on it .

**Comment by Jay-1409** [comment]
ok great do share it once u complete it thanks!!

**Comment by pragyananda** [comment]
yup.

**Comment by Srijan25** [comment]
if the work is not done can you assign it to me

**Comment by Jay-1409** [comment]
@pragyananda are you still working on it or can I pass it on?

**Comment by pragyananda** [comment]
yeah i ll generate PR on to day I just completed .
