### ISSUE TITLE
Improve the chat character page

### ISSUE THREAD

**Issue by Jay-1409** [Jay-1409/GTA5CHAT#21]

**Comment by tummavikas** [comment]
hello @Jay-1409 i want to contribute to your repo, can you assign me this issue .
I would change the layout of characters to a grid.

**Comment by Jay-1409** [comment]
@tummavikas The grid page is already present plus I wanted to change the chat character page not the home page

**Comment by Srijan25** [comment]
can you assign it to me i will make some improvement.there are some issue that i found that if you do more chat the music option hide in background so you can't stop the song and also i can change some layout

**Comment by Jay-1409** [comment]
> can you assign it to me i will make some improvement.there are some issue that i found that if you do more chat the music option hide in background so you can't stop the song and also i can change some layout

Okay thank you

**Comment by Srijan25** [comment]
![image](https://github.com/user-attachments/assets/440f65af-8f72-492f-a65b-9710d8d41da5)
 chat page has many issues . realted to image and position also it will take sometime

**Comment by Jay-1409** [comment]
Ok but please try to completed soon

**Comment by Srijan25** [comment]
It's already done

**Comment by Srijan25** [comment]
is it not in hackoberfest for my PR? becuase its not showing any tags

**Comment by Jay-1409** [comment]
> is it not in hackoberfest for my PR? becuase its not showing any tags

I added the label now.
