### ISSUE TITLE
Improve Login / Signup Form

### ISSUE THREAD

**Issue by Trishank7409** [Jay-1409/GTA5CHAT#4]
- [x] UI form is not interactive it is not a soo good.
- [x] Add the eye tool for password visibility.
- [x] Register button is not showing properly.
- [x] No Route for Sign up to Login form.
![Screenshot 2024-10-05 090449](https://github.com/user-attachments/assets/6a7977cb-169d-4f5c-89ae-57ab3bc6c480)
![Screenshot 2024-10-05 091036](https://github.com/user-attachments/assets/893b8a4b-f2a3-4147-af09-20ab995957be)

**Comment by Trishank7409** [comment]
Hey @Jay-1409 could you assign me this issue so that i can build the interactive UI and fix these points. And please add the label for Hectober-accepted.

**Comment by Jay-1409** [comment]
okay please do the changes thank you

**Comment by Srijan25** [comment]
Hey can you assign me this I will make this page more creative and UI looks more good

**Comment by w0wayush** [comment]
Would like to work on this issue, assign it to me!!

**Comment by Jay-1409** [comment]
@Srijan25 are you working on it ?

**Comment by w0wayush** [comment]
@Jay-1409 assign it to me, I would like to contribute to it.

**Comment by Srijan25** [comment]
yeah i am working on it and max part is done

**Comment by Jay-1409** [comment]
> yeah i am working on it and max part is done

Would you like to take the issue of recreating the chat page ?

**Comment by Srijan25** [comment]
yeah sure i will do it please assign it to me.but it is not showing in issue can you raise one
