### ISSUE TITLE
Improvement: Character card is not properly aligned

### ISSUE THREAD

**Issue by himanshu-sheetlani** [Jay-1409/GTA5CHAT#5]
![Screenshot (593)](https://github.com/user-attachments/assets/4545479e-b806-4bdb-8f5b-7b5f895e31de)

here content height of card is not properly aligned

**Comment by Jay-1409** [comment]
PLease align them and send the screen shot

**Comment by Srijan25** [comment]
I can do the alignment very easy i studied the code assign me i will do it fast
