### ISSUE TITLE
i want to improve Info page 

### ISSUE THREAD

**Issue by Aitzaz-Hakro** [Jay-1409/GTA5CHAT#6]
![image](https://github.com/user-attachments/assets/dff2fc8d-4302-40b0-b529-57084971eb33)

**Comment by Aitzaz-Hakro** [comment]
i will add a proper linkedIn logo + clickable emails

**Comment by Jay-1409** [comment]
since the data is dummy, i dont think it would be necessary, can you come up with something more creative ?

**Comment by VAmanjain** [comment]
Hey Jay, I would like to work with this issue. Please assign it to me. 
Here Is my approach:
1. Change the background with the GTA5 Image and make the background with a glass morphism effect.
2. Change the spacing between photos and text. So It would be more readable.

Let me know if I can work on this issue.
