### ISSUE TITLE
Feat: I would like to work on the hero section

### ISSUE THREAD

**Issue by motuncoded** [Jay-1409/GTA5CHAT#8]
I would like to work on the Navbar component of the hero section by working on the navigation links.
![Los-Santos-Legends-Chat-Choose-Your-Legend-10-05-2024_07_33_AM](https://github.com/user-attachments/assets/edfffe8b-2203-4f5a-8ed1-fbbc4257f260)

**Comment by motuncoded** [comment]
Pls assign this to me

**Comment by Jay-1409** [comment]
What exactly would you like to change

**Comment by motuncoded** [comment]
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (30/30), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 7256 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
 
I am getting this when cloning the codebases... How do I resolve this?

**Comment by Jay-1409** [comment]
dud you use 'git clone https://github.com/Jay-1409/GTA5Chat'

**Comment by Jay-1409** [comment]
are you working on this or i may close this issue ?

**Comment by motuncoded** [comment]
Pls close the issue
